TEST_VALUE:
  name: cookie
MYSQL_CONFIG:
  name: "chat-room"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "new_schema"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
  auth: "xxxx"       # redis 连接密码
  db: 1              # redis 数据库
